name: sublora
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.05.30=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.9=h7f8727e_0
  - pip=23.2.1=py38h06a4308_0
  - python=3.8.17=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==1.4.0
      - accelerate==0.21.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.1
      - appdirs==1.4.4
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - async-lru==2.0.4
      - async-timeout==4.0.2
      - attrs==23.1.0
      - babel==2.12.1
      - backcall==0.2.0
      - backoff==2.2.1
      - beautifulsoup4==4.12.2
      - bitsandbytes==0.41.1
      - bleach==6.0.0
      - boto3==1.28.17
      - botocore==1.31.17
      - bravado==11.0.3
      - bravado-core==6.1.0
      - certifi==2023.7.22
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - cmake==3.27.0
      - comm==0.1.3
      - datasets==2.14.2
      - debugpy==1.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - einops==0.6.1
      - evaluate==0.4.0
      - exceptiongroup==1.1.2
      - executing==1.2.0
      - fancycompleter==0.9.1
      - fastjsonschema==2.18.0
      - filelock==3.12.2
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - future==0.18.3
      - gitdb==4.0.10
      - gitpython==3.1.32
      - huggingface-hub==0.16.4
      - hydra-core==1.3.2
      - idna==3.4
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.0
      - ipykernel==6.25.0
      - ipython==8.12.2
      - isoduration==20.11.0
      - jedi==0.19.0
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.3.1
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonref==1.1.0
      - jsonschema==4.18.4
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.3.0
      - jupyter-core==5.3.1
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.3
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.24.0
      - lit==16.0.6
      - loralib==0.1.1
      - markupsafe==2.1.3
      - matplotlib-inline==0.1.6
      - mistune==3.0.1
      - monotonic==1.6
      - mpmath==1.3.0
      - msgpack==1.0.5
      - multidict==6.0.4
      - multiprocess==0.70.15
      - nbclient==0.8.0
      - nbconvert==7.7.3
      - nbformat==5.9.2
      - neptune==1.4.1
      - nest-asyncio==1.5.7
      - networkx==3.1
      - nltk==3.8.1
      - notebook==7.0.1
      - notebook-shim==0.2.3
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - overrides==7.3.1
      - packaging==23.1
      - pandas==2.0.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pdbpp==0.10.3
      - peft==0.4.0
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.10.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==3.20.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==12.0.1
      - pycparser==2.21
      - pygments==2.15.1
      - pyjwt==2.8.0
      - pynvml==11.5.0
      - pyrepl==0.9.0
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3
      - pyyaml==6.0.1
      - pyzmq==25.1.0
      - referencing==0.30.0
      - regex==2023.6.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987==1.3.8
      - rouge-score==0.1.2
      - rpds-py==0.9.2
      - s3transfer==0.6.1
      - safetensors==0.3.1
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - send2trash==1.8.2
      - sentencepiece==0.1.99
      - sentry-sdk==1.30.0
      - setproctitle==1.3.2
      - simplejson==3.19.1
      - six==1.16.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - swagger-spec-validator==3.0.3
      - sympy==1.12
      - terminado==0.17.1
      - threadpoolctl==3.2.0
      - tinycss2==1.2.1
      - tokenizers==0.13.3
      - tomli==2.0.1
      - torch==2.0.1
      - tornado==6.3.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - transformers==4.31.0
      - triton==2.0.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==1.26.16
      - wandb==0.15.3
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.1
      - wmctrl==0.4
      - xxhash==3.3.0
      - yarl==1.9.2
      - zipp==3.16.2
